### ISSUE TITLE
ao exporta quando roda olha o erro

### ISSUE THREAD

**Issue by DEFDaniel** [toffesource/Godot-Game-Engine-PlayerInventory#1]

**Comment by toffesource** [comment]
Hello, I had to use Google translate to understand. It seems like you're having problems when exporting the project? Can I know what version of Godot you are using?

**Comment by DEFDaniel** [comment]
It was not a mistake that when I exported to some platform I was not
working anymore I already researched and got the json file or the export
models, thank you

Em Seg, 27 de ago de 2018 19:27, Toffe <notifications@github.com> escreveu:
