### ISSUE TITLE
Moving item over the same item

### ISSUE THREAD

**Issue by Skybic** [toffesource/Godot-Game-Engine-PlayerInventory#2]
When i try placing an object on equal object (drill over the drill for example), the program always freezes.

![2019-03-28 142144](https://user-images.githubusercontent.com/49030198/55161085-03465b00-5165-11e9-8a1d-ea42409cc358.png)

**Comment by toffesource** [comment]
Thanks for bringing it up. I've updated the 3.1 project and fixed that issue.
