### ISSUE TITLE
Json loaded on every get_item call.

### ISSUE THREAD

**Issue by zcaliptium** [toffesource/Godot-Game-Engine-PlayerInventory#3]
We can see that ``Global_ItemDatabase.get_item`` called very frequent.

Problem is you do THIS every time:
```
	var itemData = {}
	itemData = Global_DataParser.load_data(url_database_item)
```
You parse data from the JSON on every method call. WTF is this?
That is just wasted CPU time and also may cause serious performance impact.

Stuff like items database should be loaded just ONCE on game startup.
So... There should be some caching for that data.

**Comment by toffesource** [comment]
Well that was embarrassing, thanks for pointing it out. I'll get on it as soon as I can.
