### ISSUE TITLE
Incorrect amount shown on new stack after split

### ISSUE THREAD

**Issue by ErsatzErmine** [toffesource/Godot-Game-Engine-PlayerInventory#5]
Steps to reproduce:

- Create a stack of 7 Tea Cups (item 3)
- Split 1 off that stack
- Split 2 off the stack of 6
- You now have stacks of 4, 1, and 2
- Right-click on each stack. Each will show a quantity of 4 on the Drop button
- Move the stack of 2 to another slot
- Right-click each stack. Each will show a quantity of 2 on the Drop button
- You can now split the stack of 1 into stacks of 0 and 1

Proposed fix:
In Script_PlayerInventory.gd

Change
var itemMetaData = Global_ItemDatabase.get_item(str(inventoryItem["id"]))
to
var itemMetaData = Global_ItemDatabase.get_item(str(inventoryItem["id"])).duplicate()

Thanks for creating and sharing this project!

**Comment by toffesource** [comment]
Thank you very much for noticing and at the same time proposing a solution to this bug. I have implemented what you have proposed and by the looks of it, the issue has been resolved.
